export interface Element {
  name: string;
  symbol: string;
  atomicNumber: number;
  atomicMass: number;
  color: string;
  radius: number;
  category:
    | "alkali"
    | "alkaline-earth"
    | "transition-metal"
    | "post-transition-metal"
    | "metalloid"
    | "nonmetal"
    | "halogen"
    | "noble-gas"
    | "lanthanide"
    | "actinide";
  description: string;
  discovered: string;
  alchemicalSymbol?: string;
  group?: number;
  period: number;
  electronConfiguration: string;
  meltingPoint?: number; // Kelvin
  boilingPoint?: number; // Kelvin
}

export const elements: Record<string, Element> = {
  // Period 1
  H: {
    name: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    atomicMass: 1.008,
    color: "#FFFFFF",
    radius: 0.53,
    category: "nonmetal",
    description:
      "The lightest and most abundant element in the universe. Essential for water and organic compounds.",
    discovered: "1766",
    alchemicalSymbol: "🜄",
    group: 1,
    period: 1,
    electronConfiguration: "1s¹",
    meltingPoint: 14.01,
    boilingPoint: 20.28,
  },
  He: {
    name: "Helium",
    symbol: "He",
    atomicNumber: 2,
    atomicMass: 4.003,
    color: "#D9FFFF",
    radius: 0.31,
    category: "noble-gas",
    description:
      "A noble gas that makes your voice squeaky. Used in balloons and as a coolant.",
    discovered: "1895",
    group: 18,
    period: 1,
    electronConfiguration: "1s²",
    meltingPoint: 0.95,
    boilingPoint: 4.22,
  },

  // Period 2
  Li: {
    name: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    atomicMass: 6.94,
    color: "#CC80FF",
    radius: 1.67,
    category: "alkali",
    description:
      "The lightest metal. Used in batteries and mood-stabilizing medications.",
    discovered: "1817",
    group: 1,
    period: 2,
    electronConfiguration: "[He] 2s¹",
    meltingPoint: 453.69,
    boilingPoint: 1615,
  },
  Be: {
    name: "Beryllium",
    symbol: "Be",
    atomicNumber: 4,
    atomicMass: 9.012,
    color: "#C2FF00",
    radius: 1.12,
    category: "alkaline-earth",
    description:
      "A lightweight, strong metal used in aerospace applications. Highly toxic.",
    discovered: "1797",
    group: 2,
    period: 2,
    electronConfiguration: "[He] 2s²",
    meltingPoint: 1560,
    boilingPoint: 2742,
  },
  B: {
    name: "Boron",
    symbol: "B",
    atomicNumber: 5,
    atomicMass: 10.81,
    color: "#FFB5B5",
    radius: 0.87,
    category: "metalloid",
    description:
      "A metalloid essential for plant growth. Used in glass and ceramics.",
    discovered: "1808",
    group: 13,
    period: 2,
    electronConfiguration: "[He] 2s² 2p¹",
    meltingPoint: 2349,
    boilingPoint: 4200,
  },
  C: {
    name: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    atomicMass: 12.01,
    color: "#909090",
    radius: 0.67,
    category: "nonmetal",
    description:
      "The basis of all organic life. Forms diamonds, graphite, and countless compounds.",
    discovered: "Ancient",
    alchemicalSymbol: "🜁",
    group: 14,
    period: 2,
    electronConfiguration: "[He] 2s² 2p²",
    meltingPoint: 3823,
    boilingPoint: 4098,
  },
  N: {
    name: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    atomicMass: 14.01,
    color: "#3050F8",
    radius: 0.56,
    category: "nonmetal",
    description:
      "Makes up 78% of Earth's atmosphere. Essential for proteins and DNA.",
    discovered: "1772",
    group: 15,
    period: 2,
    electronConfiguration: "[He] 2s² 2p³",
    meltingPoint: 63.15,
    boilingPoint: 77.36,
  },
  O: {
    name: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    atomicMass: 16.0,
    color: "#FF0D0D",
    radius: 0.48,
    category: "nonmetal",
    description:
      "Essential for respiration and combustion. Makes up 21% of Earth's atmosphere.",
    discovered: "1774",
    alchemicalSymbol: "🜃",
    group: 16,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁴",
    meltingPoint: 54.36,
    boilingPoint: 90.2,
  },
  F: {
    name: "Fluorine",
    symbol: "F",
    atomicNumber: 9,
    atomicMass: 19.0,
    color: "#90E050",
    radius: 0.42,
    category: "halogen",
    description: "The most electronegative element. Highly reactive and toxic.",
    discovered: "1886",
    group: 17,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁵",
    meltingPoint: 53.53,
    boilingPoint: 85.03,
  },
  Ne: {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    atomicMass: 20.18,
    color: "#B3E3F5",
    radius: 0.38,
    category: "noble-gas",
    description:
      "A noble gas famous for its bright orange-red glow in neon signs.",
    discovered: "1898",
    group: 18,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁶",
    meltingPoint: 24.56,
    boilingPoint: 27.07,
  },

  // Period 3
  Na: {
    name: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    atomicMass: 22.99,
    color: "#AB5CF2",
    radius: 1.9,
    category: "alkali",
    description:
      "Highly reactive metal that explodes in water. Essential for nerve function.",
    discovered: "1807",
    alchemicalSymbol: "🜔",
    group: 1,
    period: 3,
    electronConfiguration: "[Ne] 3s¹",
    meltingPoint: 370.87,
    boilingPoint: 1156,
  },
  Mg: {
    name: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    atomicMass: 24.31,
    color: "#8AFF00",
    radius: 1.45,
    category: "alkaline-earth",
    description:
      "Burns with a brilliant white light. Essential for chlorophyll in plants.",
    discovered: "1755",
    group: 2,
    period: 3,
    electronConfiguration: "[Ne] 3s²",
    meltingPoint: 923,
    boilingPoint: 1363,
  },
  Al: {
    name: "Aluminum",
    symbol: "Al",
    atomicNumber: 13,
    atomicMass: 26.98,
    color: "#BFA6A6",
    radius: 1.18,
    category: "post-transition-metal",
    description:
      "Lightweight metal used in aircraft and cans. Most abundant metal in Earth's crust.",
    discovered: "1825",
    group: 13,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p¹",
    meltingPoint: 933.47,
    boilingPoint: 2792,
  },
  Si: {
    name: "Silicon",
    symbol: "Si",
    atomicNumber: 14,
    atomicMass: 28.09,
    color: "#F0C8A0",
    radius: 1.11,
    category: "metalloid",
    description:
      "The foundation of computer chips and glass. Second most abundant element in Earth's crust.",
    discovered: "1824",
    group: 14,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p²",
    meltingPoint: 1687,
    boilingPoint: 3538,
  },
  P: {
    name: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    atomicMass: 30.97,
    color: "#FF8000",
    radius: 0.98,
    category: "nonmetal",
    description:
      "Essential for DNA, bones, and energy storage in cells. Can glow in the dark.",
    discovered: "1669",
    group: 15,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p³",
    meltingPoint: 317.3,
    boilingPoint: 553.65,
  },
  S: {
    name: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    atomicMass: 32.07,
    color: "#FFFF30",
    radius: 0.88,
    category: "nonmetal",
    description:
      "Known since ancient times. Essential for proteins and has a distinctive rotten egg smell.",
    discovered: "Ancient",
    alchemicalSymbol: "🜍",
    group: 16,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁴",
    meltingPoint: 388.36,
    boilingPoint: 717.87,
  },
  Cl: {
    name: "Chlorine",
    symbol: "Cl",
    atomicNumber: 17,
    atomicMass: 35.45,
    color: "#1FF01F",
    radius: 0.79,
    category: "halogen",
    description:
      "A toxic yellow-green gas used for water purification and bleaching.",
    discovered: "1774",
    group: 17,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁵",
    meltingPoint: 171.6,
    boilingPoint: 239.11,
  },
  Ar: {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    atomicMass: 39.95,
    color: "#80D1E3",
    radius: 0.71,
    category: "noble-gas",
    description:
      "An inert gas making up about 1% of Earth's atmosphere. Used in welding.",
    discovered: "1894",
    group: 18,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁶",
    meltingPoint: 83.8,
    boilingPoint: 87.3,
  },

  // Period 4
  K: {
    name: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    atomicMass: 39.1,
    color: "#8F40D4",
    radius: 2.43,
    category: "alkali",
    description:
      "Essential for plant growth and human health. Burns with a violet flame.",
    discovered: "1807",
    group: 1,
    period: 4,
    electronConfiguration: "[Ar] 4s¹",
    meltingPoint: 336.53,
    boilingPoint: 1032,
  },
  Ca: {
    name: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    atomicMass: 40.08,
    color: "#3DFF00",
    radius: 1.94,
    category: "alkaline-earth",
    description:
      "Essential for bones and teeth. Makes water 'hard' and enables muscle contractions.",
    discovered: "1808",
    group: 2,
    period: 4,
    electronConfiguration: "[Ar] 4s²",
    meltingPoint: 1115,
    boilingPoint: 1757,
  },
  Sc: {
    name: "Scandium",
    symbol: "Sc",
    atomicNumber: 21,
    atomicMass: 44.96,
    color: "#E6E6E6",
    radius: 1.84,
    category: "transition-metal",
    description:
      "A rare earth metal used in aerospace alloys and high-intensity lights.",
    discovered: "1879",
    group: 3,
    period: 4,
    electronConfiguration: "[Ar] 3d¹ 4s²",
    meltingPoint: 1814,
    boilingPoint: 3109,
  },
  Ti: {
    name: "Titanium",
    symbol: "Ti",
    atomicNumber: 22,
    atomicMass: 47.87,
    color: "#BFC2C7",
    radius: 1.76,
    category: "transition-metal",
    description:
      "Strong, lightweight, and corrosion-resistant. Used in aircraft and medical implants.",
    discovered: "1791",
    group: 4,
    period: 4,
    electronConfiguration: "[Ar] 3d² 4s²",
    meltingPoint: 1941,
    boilingPoint: 3560,
  },
  V: {
    name: "Vanadium",
    symbol: "V",
    atomicNumber: 23,
    atomicMass: 50.94,
    color: "#A6A6AB",
    radius: 1.71,
    category: "transition-metal",
    description:
      "Used to strengthen steel alloys. Named after the Norse goddess of beauty.",
    discovered: "1801",
    group: 5,
    period: 4,
    electronConfiguration: "[Ar] 3d³ 4s²",
    meltingPoint: 2183,
    boilingPoint: 3680,
  },
  Cr: {
    name: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    atomicMass: 52.0,
    color: "#8A99C7",
    radius: 1.66,
    category: "transition-metal",
    description:
      "Used for chrome plating and stainless steel. Gives rubies their red color.",
    discovered: "1797",
    group: 6,
    period: 4,
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    meltingPoint: 2180,
    boilingPoint: 2944,
  },
  Mn: {
    name: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    atomicMass: 54.94,
    color: "#9C7AC7",
    radius: 1.61,
    category: "transition-metal",
    description:
      "Essential for steel production and plant photosynthesis. Gives amethyst its purple color.",
    discovered: "1774",
    group: 7,
    period: 4,
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    meltingPoint: 1519,
    boilingPoint: 2334,
  },
  Fe: {
    name: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    atomicMass: 55.85,
    color: "#E06633",
    radius: 1.56,
    category: "transition-metal",
    description:
      "The most common metal on Earth. Essential for blood and steel production.",
    discovered: "Ancient",
    alchemicalSymbol: "♂",
    group: 8,
    period: 4,
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    meltingPoint: 1811,
    boilingPoint: 3134,
  },
  Co: {
    name: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    atomicMass: 58.93,
    color: "#F090A0",
    radius: 1.52,
    category: "transition-metal",
    description:
      "Used in high-strength alloys and blue pigments. Essential for vitamin B12.",
    discovered: "1735",
    group: 9,
    period: 4,
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    meltingPoint: 1768,
    boilingPoint: 3200,
  },
  Ni: {
    name: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    atomicMass: 58.69,
    color: "#50D050",
    radius: 1.49,
    category: "transition-metal",
    description:
      "Corrosion-resistant metal used in coins and stainless steel. Can cause allergies.",
    discovered: "1751",
    group: 10,
    period: 4,
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    meltingPoint: 1728,
    boilingPoint: 3186,
  },
  Cu: {
    name: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    atomicMass: 63.55,
    color: "#C88033",
    radius: 1.45,
    category: "transition-metal",
    description:
      "Excellent conductor of electricity. Turns green when oxidized (Statue of Liberty).",
    discovered: "Ancient",
    alchemicalSymbol: "♀",
    group: 11,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    meltingPoint: 1357.77,
    boilingPoint: 2835,
  },
  Zn: {
    name: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    atomicMass: 65.38,
    color: "#7D80B0",
    radius: 1.42,
    category: "transition-metal",
    description:
      "Used to galvanize steel and in batteries. Essential for immune function.",
    discovered: "Ancient",
    group: 12,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    meltingPoint: 692.68,
    boilingPoint: 1180,
  },
  Ga: {
    name: "Gallium",
    symbol: "Ga",
    atomicNumber: 31,
    atomicMass: 69.72,
    color: "#C28F8F",
    radius: 1.36,
    category: "post-transition-metal",
    description:
      "Melts in your hand at 29.8°C. Used in semiconductors and LEDs.",
    discovered: "1875",
    group: 13,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    meltingPoint: 302.91,
    boilingPoint: 2477,
  },
  Ge: {
    name: "Germanium",
    symbol: "Ge",
    atomicNumber: 32,
    atomicMass: 72.63,
    color: "#668F8F",
    radius: 1.25,
    category: "metalloid",
    description:
      "A semiconductor used in transistors and fiber optics. Predicted by Mendeleev.",
    discovered: "1886",
    group: 14,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    meltingPoint: 1211.4,
    boilingPoint: 3106,
  },
  As: {
    name: "Arsenic",
    symbol: "As",
    atomicNumber: 33,
    atomicMass: 74.92,
    color: "#BD80E3",
    radius: 1.14,
    category: "metalloid",
    description:
      "A toxic metalloid historically used as poison. Now used in semiconductors.",
    discovered: "Ancient",
    group: 15,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    meltingPoint: 1090,
    boilingPoint: 887,
  },
  Se: {
    name: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    atomicMass: 78.97,
    color: "#FFA100",
    radius: 1.03,
    category: "nonmetal",
    description:
      "Essential trace element with antioxidant properties. Conducts electricity when illuminated.",
    discovered: "1817",
    group: 16,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    meltingPoint: 494,
    boilingPoint: 958,
  },
  Br: {
    name: "Bromine",
    symbol: "Br",
    atomicNumber: 35,
    atomicMass: 79.9,
    color: "#A62929",
    radius: 0.94,
    category: "halogen",
    description:
      "The only nonmetal that's liquid at room temperature. Has a strong, unpleasant odor.",
    discovered: "1826",
    group: 17,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    meltingPoint: 265.8,
    boilingPoint: 332.0,
  },
  Kr: {
    name: "Krypton",
    symbol: "Kr",
    atomicNumber: 36,
    atomicMass: 83.8,
    color: "#5CB3D1",
    radius: 0.88,
    category: "noble-gas",
    description: "A noble gas used in high-performance light bulbs and lasers.",
    discovered: "1898",
    group: 18,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    meltingPoint: 115.79,
    boilingPoint: 119.93,
  },

  // Period 5
  Rb: {
    name: "Rubidium",
    symbol: "Rb",
    atomicNumber: 37,
    atomicMass: 85.47,
    color: "#702EB0",
    radius: 2.65,
    category: "alkali",
    description:
      "Highly reactive alkali metal that ignites spontaneously in air.",
    discovered: "1861",
    group: 1,
    period: 5,
    electronConfiguration: "[Kr] 5s¹",
    meltingPoint: 312.46,
    boilingPoint: 961,
  },
  Sr: {
    name: "Strontium",
    symbol: "Sr",
    atomicNumber: 38,
    atomicMass: 87.62,
    color: "#00FF00",
    radius: 2.19,
    category: "alkaline-earth",
    description:
      "Burns with a brilliant red flame. Used in fireworks and flares.",
    discovered: "1790",
    group: 2,
    period: 5,
    electronConfiguration: "[Kr] 5s²",
    meltingPoint: 1050,
    boilingPoint: 1655,
  },
  Y: {
    name: "Yttrium",
    symbol: "Y",
    atomicNumber: 39,
    atomicMass: 88.91,
    color: "#94FFFF",
    radius: 2.12,
    category: "transition-metal",
    description: "Used in red phosphors for TV screens and superconductors.",
    discovered: "1794",
    group: 3,
    period: 5,
    electronConfiguration: "[Kr] 4d¹ 5s²",
    meltingPoint: 1799,
    boilingPoint: 3203,
  },
  Zr: {
    name: "Zirconium",
    symbol: "Zr",
    atomicNumber: 40,
    atomicMass: 91.22,
    color: "#94E0E0",
    radius: 2.06,
    category: "transition-metal",
    description:
      "Extremely corrosion-resistant. Used in nuclear reactors and dental implants.",
    discovered: "1789",
    group: 4,
    period: 5,
    electronConfiguration: "[Kr] 4d² 5s²",
    meltingPoint: 2128,
    boilingPoint: 4682,
  },
  Nb: {
    name: "Niobium",
    symbol: "Nb",
    atomicNumber: 41,
    atomicMass: 92.91,
    color: "#73C2C9",
    radius: 1.98,
    category: "transition-metal",
    description: "Superconducting metal used in MRI magnets and jewelry.",
    discovered: "1801",
    group: 5,
    period: 5,
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    meltingPoint: 2750,
    boilingPoint: 5017,
  },
  Mo: {
    name: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    atomicMass: 95.95,
    color: "#54B5B5",
    radius: 1.9,
    category: "transition-metal",
    description:
      "Essential trace element. Used to strengthen steel and in lubricants.",
    discovered: "1778",
    group: 6,
    period: 5,
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    meltingPoint: 2896,
    boilingPoint: 4912,
  },
  Tc: {
    name: "Technetium",
    symbol: "Tc",
    atomicNumber: 43,
    atomicMass: 98,
    color: "#3B9E9E",
    radius: 1.83,
    category: "transition-metal",
    description:
      "The first artificially produced element. All isotopes are radioactive.",
    discovered: "1937",
    group: 7,
    period: 5,
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    meltingPoint: 2430,
    boilingPoint: 4538,
  },
  Ru: {
    name: "Ruthenium",
    symbol: "Ru",
    atomicNumber: 44,
    atomicMass: 101.07,
    color: "#248F8F",
    radius: 1.78,
    category: "transition-metal",
    description:
      "A rare platinum group metal used in electronics and catalysts.",
    discovered: "1844",
    group: 8,
    period: 5,
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    meltingPoint: 2607,
    boilingPoint: 4423,
  },
  Rh: {
    name: "Rhodium",
    symbol: "Rh",
    atomicNumber: 45,
    atomicMass: 102.91,
    color: "#0A7D8C",
    radius: 1.73,
    category: "transition-metal",
    description:
      "One of the rarest and most expensive metals. Used in catalytic converters.",
    discovered: "1803",
    group: 9,
    period: 5,
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    meltingPoint: 2237,
    boilingPoint: 3968,
  },
  Pd: {
    name: "Palladium",
    symbol: "Pd",
    atomicNumber: 46,
    atomicMass: 106.42,
    color: "#006985",
    radius: 1.69,
    category: "transition-metal",
    description:
      "Absorbs hydrogen like a sponge. Used in catalysts and jewelry.",
    discovered: "1803",
    group: 10,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰",
    meltingPoint: 1828.05,
    boilingPoint: 3236,
  },
  Ag: {
    name: "Silver",
    symbol: "Ag",
    atomicNumber: 47,
    atomicMass: 107.87,
    color: "#C0C0C0",
    radius: 1.65,
    category: "transition-metal",
    description:
      "The best conductor of electricity. Has natural antibacterial properties.",
    discovered: "Ancient",
    alchemicalSymbol: "☽",
    group: 11,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    meltingPoint: 1234.93,
    boilingPoint: 2435,
  },
  Cd: {
    name: "Cadmium",
    symbol: "Cd",
    atomicNumber: 48,
    atomicMass: 112.41,
    color: "#FFD98F",
    radius: 1.61,
    category: "transition-metal",
    description:
      "Toxic heavy metal used in batteries and pigments. Being phased out.",
    discovered: "1817",
    group: 12,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    meltingPoint: 594.22,
    boilingPoint: 1040,
  },
  In: {
    name: "Indium",
    symbol: "In",
    atomicNumber: 49,
    atomicMass: 114.82,
    color: "#A67573",
    radius: 1.56,
    category: "post-transition-metal",
    description:
      "Soft metal that sticks to glass. Used in touchscreens and LEDs.",
    discovered: "1863",
    group: 13,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    meltingPoint: 429.75,
    boilingPoint: 2345,
  },
  Sn: {
    name: "Tin",
    symbol: "Sn",
    atomicNumber: 50,
    atomicMass: 118.71,
    color: "#668080",
    radius: 1.45,
    category: "post-transition-metal",
    description:
      "Used since ancient times for bronze and tin cans. Makes a 'tin cry' when bent.",
    discovered: "Ancient",
    group: 14,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    meltingPoint: 505.08,
    boilingPoint: 2875,
  },
  Sb: {
    name: "Antimony",
    symbol: "Sb",
    atomicNumber: 51,
    atomicMass: 121.76,
    color: "#9E63B5",
    radius: 1.33,
    category: "metalloid",
    description:
      "Ancient cosmetic and poison. Now used in flame retardants and electronics.",
    discovered: "Ancient",
    group: 15,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    meltingPoint: 903.78,
    boilingPoint: 1860,
  },
  Te: {
    name: "Tellurium",
    symbol: "Te",
    atomicNumber: 52,
    atomicMass: 127.6,
    color: "#D47A00",
    radius: 1.23,
    category: "metalloid",
    description:
      "Rare metalloid that makes breath smell like garlic. Used in solar cells.",
    discovered: "1782",
    group: 16,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    meltingPoint: 722.66,
    boilingPoint: 1261,
  },
  I: {
    name: "Iodine",
    symbol: "I",
    atomicNumber: 53,
    atomicMass: 126.9,
    color: "#940094",
    radius: 1.15,
    category: "halogen",
    description:
      "Essential for thyroid function. Produces beautiful purple vapor when heated.",
    discovered: "1811",
    group: 17,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    meltingPoint: 386.85,
    boilingPoint: 457.4,
  },
  Xe: {
    name: "Xenon",
    symbol: "Xe",
    atomicNumber: 54,
    atomicMass: 131.29,
    color: "#429EB0",
    radius: 1.08,
    category: "noble-gas",
    description: "Noble gas used in high-intensity lamps and anesthesia.",
    discovered: "1898",
    group: 18,
    period: 5,
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    meltingPoint: 161.4,
    boilingPoint: 165.03,
  },

  // Period 6
  Cs: {
    name: "Cesium",
    symbol: "Cs",
    atomicNumber: 55,
    atomicMass: 132.91,
    color: "#57178F",
    radius: 2.98,
    category: "alkali",
    description:
      "The most reactive metal. Used in atomic clocks for precise timekeeping.",
    discovered: "1860",
    group: 1,
    period: 6,
    electronConfiguration: "[Xe] 6s¹",
    meltingPoint: 301.59,
    boilingPoint: 944,
  },
  Ba: {
    name: "Barium",
    symbol: "Ba",
    atomicNumber: 56,
    atomicMass: 137.33,
    color: "#00C900",
    radius: 2.53,
    category: "alkaline-earth",
    description:
      "Burns with a green flame. Used in fireworks and medical imaging.",
    discovered: "1808",
    group: 2,
    period: 6,
    electronConfiguration: "[Xe] 6s²",
    meltingPoint: 1000,
    boilingPoint: 2170,
  },

  // Lanthanides
  La: {
    name: "Lanthanum",
    symbol: "La",
    atomicNumber: 57,
    atomicMass: 138.91,
    color: "#70D4FF",
    radius: 2.74,
    category: "lanthanide",
    description:
      "Soft rare earth metal used in camera lenses and hybrid car batteries.",
    discovered: "1839",
    group: 3,
    period: 6,
    electronConfiguration: "[Xe] 5d¹ 6s²",
    meltingPoint: 1193,
    boilingPoint: 3737,
  },
  Ce: {
    name: "Cerium",
    symbol: "Ce",
    atomicNumber: 58,
    atomicMass: 140.12,
    color: "#FFFFC7",
    radius: 2.7,
    category: "lanthanide",
    description:
      "Most abundant rare earth element. Used in catalytic converters and lighter flints.",
    discovered: "1803",
    period: 6,
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    meltingPoint: 1068,
    boilingPoint: 3716,
  },
  Pr: {
    name: "Praseodymium",
    symbol: "Pr",
    atomicNumber: 59,
    atomicMass: 140.91,
    color: "#D9FFC7",
    radius: 2.67,
    category: "lanthanide",
    description: "Rare earth metal used in aircraft engines and green glass.",
    discovered: "1885",
    period: 6,
    electronConfiguration: "[Xe] 4f³ 6s²",
    meltingPoint: 1208,
    boilingPoint: 3793,
  },
  Nd: {
    name: "Neodymium",
    symbol: "Nd",
    atomicNumber: 60,
    atomicMass: 144.24,
    color: "#C7FFC7",
    radius: 2.64,
    category: "lanthanide",
    description:
      "Creates the strongest permanent magnets. Essential for modern technology.",
    discovered: "1885",
    period: 6,
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    meltingPoint: 1297,
    boilingPoint: 3347,
  },
  Pm: {
    name: "Promethium",
    symbol: "Pm",
    atomicNumber: 61,
    atomicMass: 145,
    color: "#A3FFC7",
    radius: 2.62,
    category: "lanthanide",
    description:
      "Radioactive rare earth metal. All isotopes are artificially produced.",
    discovered: "1945",
    period: 6,
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    meltingPoint: 1315,
    boilingPoint: 3273,
  },
  Sm: {
    name: "Samarium",
    symbol: "Sm",
    atomicNumber: 62,
    atomicMass: 150.36,
    color: "#8FFFC7",
    radius: 2.59,
    category: "lanthanide",
    description: "Used in powerful permanent magnets and nuclear reactors.",
    discovered: "1879",
    period: 6,
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    meltingPoint: 1345,
    boilingPoint: 2067,
  },
  Eu: {
    name: "Europium",
    symbol: "Eu",
    atomicNumber: 63,
    atomicMass: 151.96,
    color: "#61FFC7",
    radius: 2.56,
    category: "lanthanide",
    description:
      "Most reactive rare earth metal. Used in red phosphors for TV screens.",
    discovered: "1901",
    period: 6,
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    meltingPoint: 1099,
    boilingPoint: 1802,
  },
  Gd: {
    name: "Gadolinium",
    symbol: "Gd",
    atomicNumber: 64,
    atomicMass: 157.25,
    color: "#45FFC7",
    radius: 2.54,
    category: "lanthanide",
    description:
      "Strongly magnetic rare earth metal used in MRI contrast agents.",
    discovered: "1880",
    period: 6,
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    meltingPoint: 1585,
    boilingPoint: 3546,
  },
  Tb: {
    name: "Terbium",
    symbol: "Tb",
    atomicNumber: 65,
    atomicMass: 158.93,
    color: "#30FFC7",
    radius: 2.51,
    category: "lanthanide",
    description: "Used in green phosphors and magneto-optical devices.",
    discovered: "1843",
    period: 6,
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    meltingPoint: 1629,
    boilingPoint: 3503,
  },
  Dy: {
    name: "Dysprosium",
    symbol: "Dy",
    atomicNumber: 66,
    atomicMass: 162.5,
    color: "#1FFFC7",
    radius: 2.49,
    category: "lanthanide",
    description:
      "Highly magnetic rare earth metal used in hard drives and wind turbines.",
    discovered: "1886",
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    meltingPoint: 1680,
    boilingPoint: 2840,
  },
  Ho: {
    name: "Holmium",
    symbol: "Ho",
    atomicNumber: 67,
    atomicMass: 164.93,
    color: "#00FF9C",
    radius: 2.47,
    category: "lanthanide",
    description:
      "Has the highest magnetic strength of any element. Used in lasers.",
    discovered: "1878",
    period: 6,
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    meltingPoint: 1734,
    boilingPoint: 2993,
  },
  Er: {
    name: "Erbium",
    symbol: "Er",
    atomicNumber: 68,
    atomicMass: 167.26,
    color: "#00E675",
    radius: 2.45,
    category: "lanthanide",
    description: "Used in fiber optic communications and nuclear technology.",
    discovered: "1843",
    period: 6,
    electronConfiguration: "[Xe] 4f¹² 6s²",
    meltingPoint: 1802,
    boilingPoint: 3141,
  },
  Tm: {
    name: "Thulium",
    symbol: "Tm",
    atomicNumber: 69,
    atomicMass: 168.93,
    color: "#00D452",
    radius: 2.42,
    category: "lanthanide",
    description:
      "Rarest stable rare earth element. Used in portable X-ray machines.",
    discovered: "1879",
    period: 6,
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    meltingPoint: 1818,
    boilingPoint: 2223,
  },
  Yb: {
    name: "Ytterbium",
    symbol: "Yb",
    atomicNumber: 70,
    atomicMass: 173.05,
    color: "#00BF38",
    radius: 2.4,
    category: "lanthanide",
    description: "Used in stainless steel and atomic clocks. Soft and ductile.",
    discovered: "1878",
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    meltingPoint: 1097,
    boilingPoint: 1469,
  },
  Lu: {
    name: "Lutetium",
    symbol: "Lu",
    atomicNumber: 71,
    atomicMass: 174.97,
    color: "#00AB24",
    radius: 2.25,
    category: "lanthanide",
    description:
      "Hardest and densest rare earth metal. Most expensive of all elements.",
    discovered: "1907",
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    meltingPoint: 1925,
    boilingPoint: 3675,
  },

  // Continue Period 6 transition metals
  Hf: {
    name: "Hafnium",
    symbol: "Hf",
    atomicNumber: 72,
    atomicMass: 178.49,
    color: "#4DC2FF",
    radius: 2.16,
    category: "transition-metal",
    description:
      "Extremely corrosion-resistant. Used in nuclear reactor control rods.",
    discovered: "1923",
    group: 4,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    meltingPoint: 2506,
    boilingPoint: 4876,
  },
  Ta: {
    name: "Tantalum",
    symbol: "Ta",
    atomicNumber: 73,
    atomicMass: 180.95,
    color: "#4DA6FF",
    radius: 2.09,
    category: "transition-metal",
    description:
      "Extremely corrosion-resistant. Used in medical implants and electronics.",
    discovered: "1802",
    group: 5,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    meltingPoint: 3290,
    boilingPoint: 5731,
  },
  W: {
    name: "Tungsten",
    symbol: "W",
    atomicNumber: 74,
    atomicMass: 183.84,
    color: "#2194D6",
    radius: 2.02,
    category: "transition-metal",
    description:
      "Highest melting point of all elements. Used in light bulb filaments.",
    discovered: "1783",
    group: 6,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    meltingPoint: 3695,
    boilingPoint: 5828,
  },
  Re: {
    name: "Rhenium",
    symbol: "Re",
    atomicNumber: 75,
    atomicMass: 186.21,
    color: "#267DAB",
    radius: 1.97,
    category: "transition-metal",
    description:
      "One of the rarest elements. Used in jet engine parts and catalysts.",
    discovered: "1925",
    group: 7,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    meltingPoint: 3459,
    boilingPoint: 5869,
  },
  Os: {
    name: "Osmium",
    symbol: "Os",
    atomicNumber: 76,
    atomicMass: 190.23,
    color: "#266696",
    radius: 1.92,
    category: "transition-metal",
    description:
      "Densest naturally occurring element. Forms toxic osmium tetroxide.",
    discovered: "1803",
    group: 8,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    meltingPoint: 3306,
    boilingPoint: 5285,
  },
  Ir: {
    name: "Iridium",
    symbol: "Ir",
    atomicNumber: 77,
    atomicMass: 192.22,
    color: "#175487",
    radius: 1.87,
    category: "transition-metal",
    description:
      "Second densest element. Extremely corrosion-resistant and rare.",
    discovered: "1803",
    group: 9,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    meltingPoint: 2719,
    boilingPoint: 4701,
  },
  Pt: {
    name: "Platinum",
    symbol: "Pt",
    atomicNumber: 78,
    atomicMass: 195.08,
    color: "#D0D0E0",
    radius: 1.83,
    category: "transition-metal",
    description:
      "Noble metal used in jewelry and catalytic converters. Very unreactive.",
    discovered: "1735",
    group: 10,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    meltingPoint: 2041.4,
    boilingPoint: 4098,
  },
  Au: {
    name: "Gold",
    symbol: "Au",
    atomicNumber: 79,
    atomicMass: 196.97,
    color: "#FFD123",
    radius: 1.79,
    category: "transition-metal",
    description:
      "The most noble of metals. Doesn't tarnish and has been valued throughout history.",
    discovered: "Ancient",
    alchemicalSymbol: "☉",
    group: 11,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    meltingPoint: 1337.33,
    boilingPoint: 3129,
  },
  Hg: {
    name: "Mercury",
    symbol: "Hg",
    atomicNumber: 80,
    atomicMass: 200.59,
    color: "#B8B8D0",
    radius: 1.76,
    category: "transition-metal",
    description:
      "The only metal that's liquid at room temperature. Highly toxic but fascinating.",
    discovered: "Ancient",
    alchemicalSymbol: "☿",
    group: 12,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    meltingPoint: 234.32,
    boilingPoint: 629.88,
  },
  Tl: {
    name: "Thallium",
    symbol: "Tl",
    atomicNumber: 81,
    atomicMass: 204.38,
    color: "#A6544D",
    radius: 1.56,
    category: "post-transition-metal",
    description:
      "Highly toxic heavy metal once used as rat poison. Now banned in most countries.",
    discovered: "1861",
    group: 13,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    meltingPoint: 577,
    boilingPoint: 1746,
  },
  Pb: {
    name: "Lead",
    symbol: "Pb",
    atomicNumber: 82,
    atomicMass: 207.2,
    color: "#575961",
    radius: 1.54,
    category: "post-transition-metal",
    description:
      "Dense, toxic metal once used in paint and gasoline. Alchemists' symbol for time.",
    discovered: "Ancient",
    alchemicalSymbol: "♄",
    group: 14,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    meltingPoint: 600.61,
    boilingPoint: 2022,
  },
  Bi: {
    name: "Bismuth",
    symbol: "Bi",
    atomicNumber: 83,
    atomicMass: 208.98,
    color: "#9E4FB5",
    radius: 1.43,
    category: "post-transition-metal",
    description:
      "Creates beautiful rainbow-colored crystals. Used in cosmetics and medicine.",
    discovered: "Ancient",
    group: 15,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    meltingPoint: 544.7,
    boilingPoint: 1837,
  },
  Po: {
    name: "Polonium",
    symbol: "Po",
    atomicNumber: 84,
    atomicMass: 209,
    color: "#AB5C00",
    radius: 1.35,
    category: "metalloid",
    description:
      "Highly radioactive element discovered by Marie Curie. Extremely dangerous.",
    discovered: "1898",
    group: 16,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    meltingPoint: 527,
    boilingPoint: 1235,
  },
  At: {
    name: "Astatine",
    symbol: "At",
    atomicNumber: 85,
    atomicMass: 210,
    color: "#754F45",
    radius: 1.27,
    category: "halogen",
    description:
      "Rarest naturally occurring element. Highly radioactive and unstable.",
    discovered: "1940",
    group: 17,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    meltingPoint: 575,
    boilingPoint: 610,
  },
  Rn: {
    name: "Radon",
    symbol: "Rn",
    atomicNumber: 86,
    atomicMass: 222,
    color: "#428296",
    radius: 1.2,
    category: "noble-gas",
    description:
      "Radioactive noble gas that can accumulate in basements. Health hazard.",
    discovered: "1900",
    group: 18,
    period: 6,
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    meltingPoint: 202,
    boilingPoint: 211.3,
  },

  // Period 7
  Fr: {
    name: "Francium",
    symbol: "Fr",
    atomicNumber: 87,
    atomicMass: 223,
    color: "#420066",
    radius: 3.48,
    category: "alkali",
    description: "Most unstable alkali metal. Extremely rare and radioactive.",
    discovered: "1939",
    group: 1,
    period: 7,
    electronConfiguration: "[Rn] 7s¹",
    meltingPoint: 300,
    boilingPoint: 950,
  },
  Ra: {
    name: "Radium",
    symbol: "Ra",
    atomicNumber: 88,
    atomicMass: 226,
    color: "#007D00",
    radius: 2.83,
    category: "alkaline-earth",
    description:
      "Highly radioactive element discovered by Marie Curie. Glows in the dark.",
    discovered: "1898",
    group: 2,
    period: 7,
    electronConfiguration: "[Rn] 7s²",
    meltingPoint: 973,
    boilingPoint: 2010,
  },

  // Actinides
  Ac: {
    name: "Actinium",
    symbol: "Ac",
    atomicNumber: 89,
    atomicMass: 227,
    color: "#70ABFA",
    radius: 2.6,
    category: "actinide",
    description:
      "Radioactive metal that glows blue in the dark. Used in nuclear research.",
    discovered: "1899",
    group: 3,
    period: 7,
    electronConfiguration: "[Rn] 6d¹ 7s²",
    meltingPoint: 1323,
    boilingPoint: 3471,
  },
  Th: {
    name: "Thorium",
    symbol: "Th",
    atomicNumber: 90,
    atomicMass: 232.04,
    color: "#00BAFF",
    radius: 2.37,
    category: "actinide",
    description:
      "Radioactive metal used in nuclear reactors and gas lantern mantles.",
    discovered: "1828",
    period: 7,
    electronConfiguration: "[Rn] 6d² 7s²",
    meltingPoint: 2115,
    boilingPoint: 5061,
  },
  Pa: {
    name: "Protactinium",
    symbol: "Pa",
    atomicNumber: 91,
    atomicMass: 231.04,
    color: "#00A1FF",
    radius: 2.33,
    category: "actinide",
    description:
      "Rare, toxic, and radioactive actinide with limited applications.",
    discovered: "1913",
    period: 7,
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    meltingPoint: 1841,
    boilingPoint: 4300,
  },
  U: {
    name: "Uranium",
    symbol: "U",
    atomicNumber: 92,
    atomicMass: 238.03,
    color: "#008FFF",
    radius: 2.4,
    category: "actinide",
    description:
      "Radioactive fuel for nuclear power and weapons. Naturally occurring and heavy.",
    discovered: "1789",
    period: 7,
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    meltingPoint: 1405.3,
    boilingPoint: 4404,
  },
  Np: {
    name: "Neptunium",
    symbol: "Np",
    atomicNumber: 93,
    atomicMass: 237,
    color: "#0080FF",
    radius: 2.21,
    category: "actinide",
    description:
      "First transuranium element. Radioactive and artificially produced.",
    discovered: "1940",
    period: 7,
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    meltingPoint: 917,
    boilingPoint: 4273,
  },
  Pu: {
    name: "Plutonium",
    symbol: "Pu",
    atomicNumber: 94,
    atomicMass: 244,
    color: "#006BFF",
    radius: 2.43,
    category: "actinide",
    description:
      "Fissile material used in nuclear weapons and reactors. Extremely toxic.",
    discovered: "1940",
    period: 7,
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    meltingPoint: 912.5,
    boilingPoint: 3501,
  },
  Am: {
    name: "Americium",
    symbol: "Am",
    atomicNumber: 95,
    atomicMass: 243,
    color: "#545CF2",
    radius: 2.44,
    category: "actinide",
    description:
      "Radioactive element used in smoke detectors and nuclear applications.",
    discovered: "1944",
    period: 7,
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    meltingPoint: 1449,
    boilingPoint: 2880,
  },
  Cm: {
    name: "Curium",
    symbol: "Cm",
    atomicNumber: 96,
    atomicMass: 247,
    color: "#785CE3",
    radius: 2.45,
    category: "actinide",
    description: "Radioactive actinide named after Marie and Pierre Curie.",
    discovered: "1944",
    period: 7,
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    meltingPoint: 1613,
    boilingPoint: 3383,
  },
  Bk: {
    name: "Berkelium",
    symbol: "Bk",
    atomicNumber: 97,
    atomicMass: 247,
    color: "#8A4FE3",
    radius: 2.44,
    category: "actinide",
    description: "Radioactive actinide named after Berkeley, California.",
    discovered: "1949",
    period: 7,
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    meltingPoint: 1259,
    boilingPoint: 2900,
  },
  Cf: {
    name: "Californium",
    symbol: "Cf",
    atomicNumber: 98,
    atomicMass: 251,
    color: "#A136D4",
    radius: 2.45,
    category: "actinide",
    description:
      "Radioactive actinide used in neutron sources and nuclear research.",
    discovered: "1950",
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    meltingPoint: 1173,
    boilingPoint: 1743,
  },
  Es: {
    name: "Einsteinium",
    symbol: "Es",
    atomicNumber: 99,
    atomicMass: 252,
    color: "#B31FD4",
    radius: 2.45,
    category: "actinide",
    description: "Radioactive actinide named after Albert Einstein.",
    discovered: "1952",
    period: 7,
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    meltingPoint: 1133,
    boilingPoint: 1269,
  },
  Fm: {
    name: "Fermium",
    symbol: "Fm",
    atomicNumber: 100,
    atomicMass: 257,
    color: "#B31FBA",
    radius: 2.45,
    category: "actinide",
    description: "Radioactive actinide named after Enrico Fermi.",
    discovered: "1952",
    period: 7,
    electronConfiguration: "[Rn] 5f¹² 7s²",
    meltingPoint: 1125,
    boilingPoint: 1800,
  },
  Md: {
    name: "Mendelevium",
    symbol: "Md",
    atomicNumber: 101,
    atomicMass: 258,
    color: "#B30DA6",
    radius: 2.46,
    category: "actinide",
    description: "Radioactive actinide named after Dmitri Mendeleev.",
    discovered: "1955",
    period: 7,
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    meltingPoint: 1100,
    boilingPoint: 1500,
  },
  No: {
    name: "Nobelium",
    symbol: "No",
    atomicNumber: 102,
    atomicMass: 259,
    color: "#BD0D87",
    radius: 2.46,
    category: "actinide",
    description: "Radioactive actinide named after Alfred Nobel.",
    discovered: "1957",
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    meltingPoint: 1100,
    boilingPoint: 1400,
  },
  Lr: {
    name: "Lawrencium",
    symbol: "Lr",
    atomicNumber: 103,
    atomicMass: 266,
    color: "#C70066",
    radius: 2.46,
    category: "actinide",
    description: "Radioactive actinide named after Ernest Lawrence.",
    discovered: "1961",
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
    meltingPoint: 1900,
    boilingPoint: 2500,
  },

  // Period 7 continuation - Super heavy elements
  Rf: {
    name: "Rutherfordium",
    symbol: "Rf",
    atomicNumber: 104,
    atomicMass: 267,
    color: "#CC0059",
    radius: 2.3,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Ernest Rutherford.",
    discovered: "1964",
    group: 4,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    meltingPoint: 2400,
    boilingPoint: 5800,
  },
  Db: {
    name: "Dubnium",
    symbol: "Db",
    atomicNumber: 105,
    atomicMass: 268,
    color: "#D1004F",
    radius: 2.25,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Dubna, Russia.",
    discovered: "1967",
    group: 5,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    meltingPoint: 2900,
    boilingPoint: 6200,
  },
  Sg: {
    name: "Seaborgium",
    symbol: "Sg",
    atomicNumber: 106,
    atomicMass: 269,
    color: "#D90045",
    radius: 2.2,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Glenn T. Seaborg.",
    discovered: "1974",
    group: 6,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    meltingPoint: 3100,
    boilingPoint: 6500,
  },
  Bh: {
    name: "Bohrium",
    symbol: "Bh",
    atomicNumber: 107,
    atomicMass: 270,
    color: "#E00038",
    radius: 2.15,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Niels Bohr.",
    discovered: "1981",
    group: 7,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    meltingPoint: 3400,
    boilingPoint: 6800,
  },
  Hs: {
    name: "Hassium",
    symbol: "Hs",
    atomicNumber: 108,
    atomicMass: 269,
    color: "#E6002E",
    radius: 2.1,
    category: "transition-metal",
    description:
      "Synthetic superheavy element named after the German state of Hesse.",
    discovered: "1984",
    group: 8,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    meltingPoint: 3700,
    boilingPoint: 7100,
  },
  Mt: {
    name: "Meitnerium",
    symbol: "Mt",
    atomicNumber: 109,
    atomicMass: 278,
    color: "#EB0026",
    radius: 2.05,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Lise Meitner.",
    discovered: "1982",
    group: 9,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    meltingPoint: 4000,
    boilingPoint: 7400,
  },
  Ds: {
    name: "Darmstadtium",
    symbol: "Ds",
    atomicNumber: 110,
    atomicMass: 281,
    color: "#F00021",
    radius: 2.0,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Darmstadt, Germany.",
    discovered: "1994",
    group: 10,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    meltingPoint: 4300,
    boilingPoint: 7700,
  },
  Rg: {
    name: "Roentgenium",
    symbol: "Rg",
    atomicNumber: 111,
    atomicMass: 282,
    color: "#F5001C",
    radius: 1.95,
    category: "transition-metal",
    description: "Synthetic superheavy element named after Wilhelm Röntgen.",
    discovered: "1994",
    group: 11,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    meltingPoint: 4600,
    boilingPoint: 8000,
  },
  Cn: {
    name: "Copernicium",
    symbol: "Cn",
    atomicNumber: 112,
    atomicMass: 285,
    color: "#FA0018",
    radius: 1.9,
    category: "transition-metal",
    description:
      "Synthetic superheavy element named after Nicolaus Copernicus.",
    discovered: "1996",
    group: 12,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    meltingPoint: 4900,
    boilingPoint: 8300,
  },
  Nh: {
    name: "Nihonium",
    symbol: "Nh",
    atomicNumber: 113,
    atomicMass: 286,
    color: "#FF0014",
    radius: 1.7,
    category: "post-transition-metal",
    description: "Synthetic superheavy element named after Japan (Nihon).",
    discovered: "2004",
    group: 13,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    meltingPoint: 700,
    boilingPoint: 1400,
  },
  Fl: {
    name: "Flerovium",
    symbol: "Fl",
    atomicNumber: 114,
    atomicMass: 289,
    color: "#FF0010",
    radius: 1.6,
    category: "post-transition-metal",
    description: "Synthetic superheavy element named after Georgy Flerov.",
    discovered: "1998",
    group: 14,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    meltingPoint: 340,
    boilingPoint: 420,
  },
  Mc: {
    name: "Moscovium",
    symbol: "Mc",
    atomicNumber: 115,
    atomicMass: 290,
    color: "#FF000C",
    radius: 1.5,
    category: "post-transition-metal",
    description: "Synthetic superheavy element named after Moscow, Russia.",
    discovered: "2003",
    group: 15,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    meltingPoint: 670,
    boilingPoint: 1400,
  },
  Lv: {
    name: "Livermorium",
    symbol: "Lv",
    atomicNumber: 116,
    atomicMass: 293,
    color: "#FF0008",
    radius: 1.4,
    category: "post-transition-metal",
    description:
      "Synthetic superheavy element named after Livermore, California.",
    discovered: "2000",
    group: 16,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    meltingPoint: 709,
    boilingPoint: 1085,
  },
  Ts: {
    name: "Tennessine",
    symbol: "Ts",
    atomicNumber: 117,
    atomicMass: 294,
    color: "#FF0005",
    radius: 1.3,
    category: "halogen",
    description: "Synthetic superheavy halogen named after Tennessee, USA.",
    discovered: "2010",
    group: 17,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    meltingPoint: 723,
    boilingPoint: 883,
  },
  Og: {
    name: "Oganesson",
    symbol: "Og",
    atomicNumber: 118,
    atomicMass: 294,
    color: "#FF0002",
    radius: 1.2,
    category: "noble-gas",
    description: "Synthetic superheavy noble gas named after Yuri Oganessian.",
    discovered: "2002",
    group: 18,
    period: 7,
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    meltingPoint: 325,
    boilingPoint: 450,
  },
};

// Element-related utility functions
export const getElementsByCategory = (
  category: Element["category"],
): Element[] => {
  return Object.values(elements).filter(
    (element) => element.category === category,
  );
};

export const getRandomElement = (): Element => {
  const elementKeys = Object.keys(elements);
  const randomKey = elementKeys[Math.floor(Math.random() * elementKeys.length)];
  return elements[randomKey];
};

export const getElementBySymbol = (symbol: string): Element | undefined => {
  return elements[symbol];
};

export const getAllElements = (): Element[] => {
  return Object.values(elements);
};

export const getPeriodElements = (period: number): Element[] => {
  return Object.values(elements).filter((element) => element.period === period);
};

export const getGroupElements = (group: number): Element[] => {
  return Object.values(elements).filter((element) => element.group === group);
};
